pub mod model;
pub mod store;
pub use model::{PromptDocument, PromptSlot};
pub use store::{PromptSnapshot, PromptStore};
mod actions;
pub mod dock;
pub mod dock_session;
pub mod dock_ui;
pub mod editor;
pub mod paste;
pub mod popup;
pub mod runtime;
pub mod ui;
